import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StrapiHeader from "@/components/Header/Header";
import StrapiForm from "@/components/Form/Form";
import StrapiFooter from "@/components/Footer/Footer";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "600", "700"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk-UA">
      <body className={manrope.className}>
        <StrapiHeader />
        {children}
        <StrapiForm />
        <StrapiFooter />
      </body>
    </html>
  );
}
