import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";
import StrapiHeader from "@/components/Header/Header";
import StrapiFooter from "@/components/Footer/Footer";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { AppLocale } from "@/types/types";
import { fetchFromStrapi } from "@/fetch/fetch";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs/Breadcrumbs";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "600", "700"],
  variable: "--font-manrope",
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = (await params) as { locale: AppLocale };

  setRequestLocale(locale);

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const headerData = await fetchFromStrapi("/header", {
    locale,
    populate: {
      links: true,
    },
  });

  return (
    <html lang={locale} className="scroll-smooth">
      <body className={manrope.className}>
        <NextIntlClientProvider>
          <StrapiHeader />
          <Breadcrumbs links={headerData.data.links} locale={locale} />
          {children}
          <StrapiFooter />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
